### ISSUE TITLE
Issue with Simple Date Component

### ISSUE THREAD

**Issue by JonasDuclos** [org-scn-design-studio-community/lumiradesignercommunityext#13]
Hello all, 

I have installed SDK Community on my local Lumira 2.0 SP02, but i'm not able to run my application which use SIMPLEDATE Component.

It seems Lumira 2.0 is not able to use rollDays function 

"Message: org.mozilla.javascript.EcmaError: ReferenceError: "internal_setDateByIndex" is not defined. (DATE.rollDays()#7)
Stack trace: com.sap.ip.bi.zen.rt.framework.jsengine.JsEngineException: org.mozilla.javascript.EcmaError: ReferenceError: "internal_setDateByIndex" is not defined. (DATE.rollDays()#7)" 

I'm not 100% sure my extension is well installed, you can see it here. (i took this link : https://github.com/org-scn-design-studio-community/lumiradesignercommunityext/blob/master/releases/org.scn.community.sdk.extensions.zip?raw=true, link found here : https://blogs.sap.com/2017/08/18/scn-lumira-designer-2.0-sdk-components/)

![image](https://user-images.githubusercontent.com/20657788/31951373-3501fb5c-b8de-11e7-8f38-3bd85181c41b.png)

Best regards ! 

Jonas.

**Comment by entmike** [comment]
Hey Jonas,

Thanks for reporting the problem.  The good news for you is that it's not your problem.  The bad news for me is that I'll need to fix something :)

Give me a day or 2 and I can create a fix.

**Comment by JonasDuclos** [comment]
Good to know i'm not responsible for this issue :D Thank for your responsiveness, i appreciate !

Good luck for this !

**Comment by entmike** [comment]
Hey Jonas,

Give it another try when you have time and let me know if it's fixed for you, now.

**Comment by JonasDuclos** [comment]
Hello Mike, 

I tried to re-download your extension but i have an issue when i try to install it

![image](https://user-images.githubusercontent.com/20657788/31986068-60cff160-b967-11e7-8978-ec9e1f4c2623.png)

I failed somewhere ?

**Comment by entmike** [comment]
I will take a look today. Perhaps try redownloading it and removing it the old version of the extension in the meantime.

**Comment by JonasDuclos** [comment]
Done but unsuccessfully :(

**Comment by entmike** [comment]
Ok yeah I screwed up the build.  I pushed a fix up if you could try to download once more and try again.

**Comment by JonasDuclos** [comment]
Great ! 

But i'm sorry, still have an issue. Seems you fixed rollDays but there is the same issue for rollDays (and i guess for others functions in this component)

Message: org.mozilla.javascript.EcmaError: ReferenceError: "getYear" is not defined. (DATE.internal_rollMonths()#11)
Stack trace: com.sap.ip.bi.zen.rt.framework.jsengine.JsEngineException: org.mozilla.javascript.EcmaError: ReferenceError: "getYear" is not defined. (DATE.internal_rollMonths()#11)

**Comment by entmike** [comment]
Let's try again.  I missed a spot, you are right.  Ready for you to download and try again.

**Comment by JonasDuclos** [comment]
Nice !
Works perfectly !

Big thank for your support Mike !

**Comment by entmike** [comment]
Glad to be able to help.  Sorry for the bugs.  Lumira 2.0 changed the way script scope worked, so I'm only hearing these issues as people are using the script APIs.  Please feel free to report any new issues you encounter going forward!  Going to close this issue as it sounds like it's been corrected.

Thanks!
